import reducers from '..'

describe('update redux state after fetching articles', () => {
    it('should update state with articles', () => {
        const state = reducers(
            { redditData: { currentSub: null, articles: [], afterPage: null } },
            {
                type: 'SET_ARTICLES',
                payload: {
                    articles: [
                        {
                            kind: 't3',
                            data: {
                                approved_at_utc: null,
                                subreddit: 'guitarpedals',
                                selftext:
                                    'What are your most keenly anticipated new releases this year?\n\nWill *you* be there?\n\nHave you heard any rumours concerning possible, upcoming pedals?\n\nAny and all NAMM-related discussion is welcome!',
                                author_fullname: 't2_k1qsp',
                                saved: false,
                                mod_reason_title: null,
                                gilded: 0,
                                clicked: false,
                                title: 'NAMM 2019 Hype Thread',
                                link_flair_richtext: [],
                                subreddit_name_prefixed: 'r/guitarpedals',
                                hidden: false,
                                pwls: 6,
                                link_flair_css_class: null,
                                downs: 0,
                                thumbnail_height: null,
                                hide_score: false,
                                name: 't3_aibcl4',
                                quarantine: false,
                                link_flair_text_color: 'dark',
                                author_flair_background_color: '',
                                subreddit_type: 'public',
                                ups: 57,
                                domain: 'self.guitarpedals',
                                media_embed: {},
                                thumbnail_width: null,
                                author_flair_template_id:
                                    '256cca3a-d93e-11e6-b696-0e21929c3848',
                                is_original_content: false,
                                user_reports: [],
                                secure_media: null,
                                is_reddit_media_domain: false,
                                is_meta: false,
                                category: null,
                                secure_media_embed: {},
                                link_flair_text: null,
                                can_mod_post: false,
                                score: 57,
                                approved_by: null,
                                thumbnail: 'self',
                                edited: false,
                                author_flair_css_class: 'ms70cdr',
                                author_flair_richtext: [],
                                gildings: { gid_1: 0, gid_2: 0, gid_3: 0 },
                                content_categories: null,
                                is_self: true,
                                mod_note: null,
                                created: 1548114782,
                                link_flair_type: 'text',
                                wls: 6,
                                banned_by: null,
                                author_flair_type: 'text',
                                contest_mode: false,
                                selftext_html:
                                    '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;What are your most keenly anticipated new releases this year?&lt;/p&gt;\n\n&lt;p&gt;Will &lt;em&gt;you&lt;/em&gt; be there?&lt;/p&gt;\n\n&lt;p&gt;Have you heard any rumours concerning possible, upcoming pedals?&lt;/p&gt;\n\n&lt;p&gt;Any and all NAMM-related discussion is welcome!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
                                likes: null,
                                suggested_sort: 'new',
                                banned_at_utc: null,
                                view_count: null,
                                archived: false,
                                no_follow: false,
                                is_crosspostable: false,
                                pinned: false,
                                over_18: false,
                                media_only: false,
                                link_flair_template_id: null,
                                can_gild: false,
                                spoiler: false,
                                locked: false,
                                author_flair_text: '',
                                visited: false,
                                num_reports: null,
                                distinguished: 'moderator',
                                subreddit_id: 't5_2r0bp',
                                mod_reason_by: null,
                                removal_reason: null,
                                link_flair_background_color: '',
                                id: 'aibcl4',
                                is_robot_indexable: true,
                                report_reasons: null,
                                author: 'slap_me_thrice',
                                num_crossposts: 0,
                                num_comments: 410,
                                send_replies: false,
                                whitelist_status: 'all_ads',
                                mod_reports: [],
                                author_patreon_flair: false,
                                author_flair_text_color: 'dark',
                                permalink:
                                    '/r/guitarpedals/comments/aibcl4/namm_2019_hype_thread/',
                                parent_whitelist_status: 'all_ads',
                                stickied: true,
                                url:
                                    'https://www.reddit.com/r/guitarpedals/comments/aibcl4/namm_2019_hype_thread/',
                                subreddit_subscribers: 81001,
                                created_utc: 1548085982,
                                media: null,
                                is_video: false
                            }
                        }
                    ],
                    currentSub: 'guitarpedals',
                    afterPage: 't3_akzvex',
                    paging: false
                }
            }
        )
        expect(state).toEqual({
            redditData: {
                articles: [
                    {
                        kind: 't3',
                        data: {
                            approved_at_utc: null,
                            subreddit: 'guitarpedals',
                            selftext:
                                'What are your most keenly anticipated new releases this year?\n\nWill *you* be there?\n\nHave you heard any rumours concerning possible, upcoming pedals?\n\nAny and all NAMM-related discussion is welcome!',
                            author_fullname: 't2_k1qsp',
                            saved: false,
                            mod_reason_title: null,
                            gilded: 0,
                            clicked: false,
                            title: 'NAMM 2019 Hype Thread',
                            link_flair_richtext: [],
                            subreddit_name_prefixed: 'r/guitarpedals',
                            hidden: false,
                            pwls: 6,
                            link_flair_css_class: null,
                            downs: 0,
                            thumbnail_height: null,
                            hide_score: false,
                            name: 't3_aibcl4',
                            quarantine: false,
                            link_flair_text_color: 'dark',
                            author_flair_background_color: '',
                            subreddit_type: 'public',
                            ups: 57,
                            domain: 'self.guitarpedals',
                            media_embed: {},
                            thumbnail_width: null,
                            author_flair_template_id:
                                '256cca3a-d93e-11e6-b696-0e21929c3848',
                            is_original_content: false,
                            user_reports: [],
                            secure_media: null,
                            is_reddit_media_domain: false,
                            is_meta: false,
                            category: null,
                            secure_media_embed: {},
                            link_flair_text: null,
                            can_mod_post: false,
                            score: 57,
                            approved_by: null,
                            thumbnail: 'self',
                            edited: false,
                            author_flair_css_class: 'ms70cdr',
                            author_flair_richtext: [],
                            gildings: { gid_1: 0, gid_2: 0, gid_3: 0 },
                            content_categories: null,
                            is_self: true,
                            mod_note: null,
                            created: 1548114782,
                            link_flair_type: 'text',
                            wls: 6,
                            banned_by: null,
                            author_flair_type: 'text',
                            contest_mode: false,
                            selftext_html:
                                '&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;What are your most keenly anticipated new releases this year?&lt;/p&gt;\n\n&lt;p&gt;Will &lt;em&gt;you&lt;/em&gt; be there?&lt;/p&gt;\n\n&lt;p&gt;Have you heard any rumours concerning possible, upcoming pedals?&lt;/p&gt;\n\n&lt;p&gt;Any and all NAMM-related discussion is welcome!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
                            likes: null,
                            suggested_sort: 'new',
                            banned_at_utc: null,
                            view_count: null,
                            archived: false,
                            no_follow: false,
                            is_crosspostable: false,
                            pinned: false,
                            over_18: false,
                            media_only: false,
                            link_flair_template_id: null,
                            can_gild: false,
                            spoiler: false,
                            locked: false,
                            author_flair_text: '',
                            visited: false,
                            num_reports: null,
                            distinguished: 'moderator',
                            subreddit_id: 't5_2r0bp',
                            mod_reason_by: null,
                            removal_reason: null,
                            link_flair_background_color: '',
                            id: 'aibcl4',
                            is_robot_indexable: true,
                            report_reasons: null,
                            author: 'slap_me_thrice',
                            num_crossposts: 0,
                            num_comments: 410,
                            send_replies: false,
                            whitelist_status: 'all_ads',
                            mod_reports: [],
                            author_patreon_flair: false,
                            author_flair_text_color: 'dark',
                            permalink:
                                '/r/guitarpedals/comments/aibcl4/namm_2019_hype_thread/',
                            parent_whitelist_status: 'all_ads',
                            stickied: true,
                            url:
                                'https://www.reddit.com/r/guitarpedals/comments/aibcl4/namm_2019_hype_thread/',
                            subreddit_subscribers: 81001,
                            created_utc: 1548085982,
                            media: null,
                            is_video: false
                        }
                    }
                ],
                currentSub: 'guitarpedals',
                afterPage: 't3_akzvex',
                paging: false
            }
        })
    })
})
